SELECT CUSTOMER_CODE
  ,CUSTOMER_NAME
  ,VENDER_CODE
  ,VENDER_NAME
  ,KA_CODE
  ,KA_NAME
  ,ORDER_FORM_AMOUNT
  ,RESPONSIBLE_PERSON
  ,ORDER_DATE
  ,ORDER_NUMBER
FROM F_KMS_ORDER_FORM_DETAIL_STG;

SELECT ORDER_FORM_ID
  ,GOODS_CODE
  ,GOODS_NAME
  ,UNIT
  ,QUANTITY
  ,UNIT_PRICE_IN_TAX
  ,AMOUNT
FROM F_KMS_ORDER_GOODS_DETAIL_STG;
